[postgres]
user = "postgres"
password = "postgres"
port = 5431
host = "localhost"
dbname = "meshtastic"
# Max and minimum connection configures how many workers can be allocated for
# performing Postgres connections. max_connections is also half of the
# incoming packets bound (maximum in-flight tasks) which is at most 32
max_connections = 8
min_connections = 1
#TODO: Add more settings

[serial]
# The path to the serial port of a connected Meshtastic node, if left blank the
# user is prompted for the path out of a list of possible paths
port = ""

[deployment]
# The name of this group of nodes
location = "testing"
